server:
  port: 8801
spring:
  application:
    name: stream-rabbitmq-producer
  profiles:
    active: partition
  # spring.cloud.nacos
  cloud:
    nacos:
      config:
        group: ICDR
        server-addr: ${NACOS_SERVER_ADDR:192.168.0.11:8098}
        file-extension: yml
      discovery:
        group: ICDR
        namespace: ${NACOS_DISCOVERY_NAMESPACE:8445c2b6-100e-4f9c-bc6f-64e75388fd9e}
        server-addr: ${NACOS_SERVER_ADDR:192.168.0.11:8098}

